# Generated by Django 3.0 on 2019-12-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sighting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='squirrel_data',
            new_name='Squirrel',
        ),
    ]
